name: Reprocessar Bancos (Sem Extração)
on:
  workflow_dispatch: # Permite que você clique no botão "Run workflow" no site

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar Dependencias
        run: pip install pandas pyarrow

      - name: 🛠️ Reprocessar apenas as bases de dados
        run: |
          python main_executor.py banco || true

      - name: 💾 Salvar Arquivos Gerados
        run: |
          git config --global user.name 'Michell-Bot'
          git config --global user.email 'tingolopes@gmail.com'
          git add *.csv
          git commit -m "Reprocessamento manual: $(date +'%Y-%m-%d %H:%M')" || exit 0
          git push